"""
Build L7 - Multivariate Analysis for Executives (narrative-first).
Calibrated against NB-02 Prescriptive (Supply Chain HHI) inputs.
Output: analise-prescritiva/learning/l7-multivariate-analysis.ipynb
"""
import json
from pathlib import Path

NOTEBOOK_PATH = Path(
    r"C:\Users\mathe\code_space\orchestration\value-factory\case-studies\byd-camacari-2025-2027\analise-prescritiva\learning\l7-multivariate-analysis.ipynb"
)

# ─────────────────────────────────────────────────────────────────────────────
# NOTEBOOK CELLS
# ─────────────────────────────────────────────────────────────────────────────
CELLS = []

# ── Cell 1: Title + meta ─────────────────────────────────────────────────────
CELLS.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# L7 · Análise Multivariada para Executivos\n",
        "**Análise Prescritiva — Camada de Alfabetização de Dados (Learning)**\n",
        "\n",
        "| Campo | Detalhe |\n",
        "|---|---|\n",
        "| **Notebook** | L7 · Multivariate Analysis for Executives |\n",
        "| **Autor** | Matheus Mendes |\n",
        "| **Data** | 27/julho/2026 |\n",
        "| **Versão** | 1.0 |\n",
        "| **Público-alvo** | Executivos não-técnicos — \"por que tudo muda junto?\" |\n",
        "| **Dependências** | numpy, pandas, plotly, scikit-learn |\n",
        "| **Fonte quantitativa** | NB-02 · Supply Chain + Lithium VaR (HHI, choques correlacionados) |\n",
        "\n",
        "---\n",
        "\n",
        "## Por que este notebook existe\n",
        "\n",
        "Em **L0** você aprendeu que a média não conta a história inteira. Em **L1**\n",
        "viu que a incerteza tem forma — uma distribuição, não um número. Em **L4**\n",
        "acompanhou o caminho de uma única variável ao longo do tempo. Em **L6**\n",
        "cruzou quatro variáveis simultaneamente em 10.000 cenários.\n",
        "\n",
        "Em **L7** damos o passo que faltava: **olhar para todas as variáveis ao\n",
        "mesmo tempo e descobrir quantas histórias independentes elas contam**. O\n",
        "case BYD tem câmbio, lítio, tarifa, demanda, frete, concentração de\n",
        "refino, alocação de células, share de CATL — oito vetores de risco. Mas\n",
        "quantos existem **de verdade**? A resposta típica em supply chain é três:\n",
        "tensão geopolítica, concentração de bateria e ritmo de mercado.\n",
        "\n",
        "A pergunta executiva de L7 não é \"quanto mede o lítio?\". É:\n",
        "\n",
        "> **\"Quantas fontes reais de risco eu tenho, e quais variáveis são apenas\n",
        "> sintomas da mesma causa?\"**\n",
        "\n",
        "Este caderno é **narrativa-primeiro**:\n",
        "\n",
        "> **Conceito → Intuição → Matemática → Código → Recado Executivo**\n",
        "\n",
        "Os números são os resultados exportados pelo **NB-02 Prescriptive (Supply\n",
        "Chain + HHI)**: três camadas de concentração (mineração HHI 2.936, refino\n",
        "HHI 4.558, células HHI 2.118), quatro choques correlacionados (PTAX,\n",
        "Lítio, Tarifa, Demanda) e quatro cenários de ruptura (CATL, Chile, TSMC,\n",
        "Logística). O tema escuro (`#0d1117`) e a paleta (`azul-petróleo ·\n",
        "vermelho-tijolo · teal · violeta · laranja-âmbar`) seguem o padrão visual\n",
        "dos cadernos anteriores.\n",
        "\n",
        "### As 8 variáveis do case BYD (NB-02 + L6)\n",
        "\n",
        "| # | Variável | Sinal de risco | Camada |\n",
        "|---|---|---|---|\n",
        "| 1 | **PTAX/FX** | vol 14,17% a.a. | câmbio (L6) |\n",
        "| 2 | **Lítio** | vol 82,9% a.a. | matéria-prima (L6) |\n",
        "| 3 | **Tarifa** | evento binário 35% | política (L6) |\n",
        "| 4 | **Demanda EV** | vol 5% a.a. | mercado (L6) |\n",
        "| 5 | **HHI refino** | 4.558 (ALTA) | concentração (NB-02) |\n",
        "| 6 | **HHI mineração** | 2.936 (ALTA) | concentração (NB-02) |\n",
        "| 7 | **Share CATL** | 37% das células | fornecedor (NB-02) |\n",
        "| 8 | **Frete marítimo** | vol mensal | logística (NB-02) |\n",
        "\n",
        "### Os 6 conceitos deste caderno\n",
        "\n",
        "| # | Conceito | Pergunta executiva |\n",
        "|---|---|---|\n",
        "| 1 | **Multivariada de verdade** | Por que olhar uma variável de cada vez mente? |\n",
        "| 2 | **Matriz de correlação** | O que se move junto com o quê? |\n",
        "| 3 | **Análise fatorial** | Quantos drivers ocultos estão atrás das oito variáveis? |\n",
        "| 4 | **Componentes principais (PCA)** | Como resumir 8 vetores em 3 sem perder o essencial? |\n",
        "| 5 | **\"Três fatores explicam 80%\"** | Como ouvir essa frase sem confundir com causalidade? |\n",
        "| 6 | **Decisão multivariada** | Como reorganizar o monitoramento quando os drivers mudam? |\n",
        "\n",
        "---\n",
        "\n",
        "## 1 · Multivariada de verdade — por que uma variável de cada vez mente\n",
        "\n",
        "### ① Por que isto importa\n",
        "\n",
        "O reflexo do executivo é receber cada risco em uma página: \"o lítio subiu\n",
        "12%\", \"o PTAX foi a R$ 5,40\", \"a CATL alocou 75%\". Cada página é correta\n",
        "e cada uma é uma meia-verdade. Quando o dólar sobe forte, o lítio tende a\n",
        "subir junto, a CATL pressiona por contratos锁定 e os fornecedores pedem\n",
        "adiantamento. Olhar variável por variável, uma atrás da outra, esconde a\n",
        "co-movimentação — e é exatamente a co-movimentação que decide o caixa.\n",
        "\n",
        "### ② Conceito, sem jargão\n",
        "\n",
        "**Análise multivariada** é olhar várias variáveis em conjunto, em vez de\n",
        "uma de cada vez. O ponto não é somar mais números — é enxergar o padrão\n",
        "que só aparece quando as variáveis estão no mesmo gráfico: clusters,\n",
        "alinhamentos, contramovimentos. Oito gráficos lado a lado são \"oito\n",
        "histórias\"; uma matriz 8×8 é \"uma história em que oito personagens\n",
        "interagem\".\n",
        "\n",
        "### ③ Intuição — o bonde e os passageiros\n",
        "\n",
        "Imagine uma avenida onde passam oito bondes. Cada bonde é uma variável.\n",
        "Alguns correm juntos (\"tensão geopolítica\"): PTAX, Tarifa, Lítio. Outros\n",
        "andam em outro ritmo (\"concentração de bateria\"): HHI refino, share CATL.\n",
        "Outros ainda respondem ao mercado: demanda EV, frete. Olhar bonde por\n",
        "bonde não revela que existem **três comboios**. Olhar a avenida toda, com\n",
        "todos os bondes no mesmo quadro, revela: **três comboios explicam quase\n",
        "toda a variação**. O executivo que olha um bonde acha que tem oito riscos;\n",
        "o executivo que olha a avenida sabe que tem três.\n",
        "\n",
        "### ④ A matemática — covariância e correlação\n",
        "\n",
        "Para duas variáveis $x$ e $y$, a **covariância** é a média do produto\n",
        "dos desvios:\n",
        "$$\\text{cov}(x,y) = \\frac{1}{n-1}\\sum_{i=1}^{n}(x_i-\\bar x)(y_i-\\bar y)$$\n",
        "A **correlação** normaliza a covariância pelo produto dos desvios-padrão:\n",
        "$$\\rho(x,y) = \\frac{\\text{cov}(x,y)}{\\sigma_x \\sigma_y}$$\n",
        "O resultado vive em $[-1, 1]$: $+1$ = andam perfeitamente juntos; $-1$\n",
        "= andam perfeitamente opostos; $0$ = independentes. No NB-02, PTAX e\n",
        "Lítio têm $\\rho \\approx 0{,}45$ — sobem juntos, mas não perfeitamente.\n",
        "\n",
        "### ⑤ Recado executivo — Multivariada\n",
        "\n",
        "> - **Um risco por slide é uma fantasia de controle.** Oito números lado a\n",
        "  lado não são oito riscos independentes — são sintomas de poucos drivers.\n",
        "> - A pergunta certa é: *\"estes números se movem juntos por quê?\"*\n",
        "> - Sempre peça: *\"mostre a matriz de correlação, não oito retas separadas.\"*\n",
    ]
})

# ── Cell 2: Setup + synthetic data ───────────────────────────────────────────
CELLS.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ──────────────────────────────────────────────────────────────────────\n",
        "# Setup — carrega NB-02 e gera 60 meses de supply chain calibrados\n",
        "# ──────────────────────────────────────────────────────────────────────\n",
        "import json\n",
        "from pathlib import Path\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import plotly.graph_objects as go\n",
        "from plotly.subplots import make_subplots\n",
        "\n",
        "# PCA enxuto em numpy — np.linalg.eigh sobre a matriz de correlação\n",
        "def pca_numpy(X_std, n_components=None):\n",
        "    R = np.corrcoef(X_std, rowvar=False)\n",
        "    vals, vecs = np.linalg.eigh(R)\n",
        "    order = np.argsort(vals)[::-1]\n",
        "    vals = vals[order]\n",
        "    vecs = vecs[:, order]\n",
        "    if n_components is not None:\n",
        "        vecs = vecs[:, :n_components]\n",
        "        vals = vals[:n_components]\n",
        "    # Convenção de sinal: flipa cada eixo para que a maior loading absoluta\n",
        "    # seja positiva — torna a leitura executiva estável\n",
        "    for j in range(vecs.shape[1]):\n",
        "        if np.abs(vecs[:, j]).max() > 0 and vecs[np.argmax(np.abs(vecs[:, j])), j] < 0:\n",
        "            vecs[:, j] = -vecs[:, j]\n",
        "    scores = X_std @ vecs\n",
        "    loadings = vecs * np.sqrt(vals)\n",
        "    return scores, loadings, vals\n",
        "\n",
        "NOTEBOOK_ROOT = Path(r\"C:\\Users\\mathe\\code_space\\orchestration\\value-factory\\case-studies\\byd-camacari-2025-2027\\analise-prescritiva\")\n",
        "if not (NOTEBOOK_ROOT / \"outputs\" / \"nb02_results.json\").exists():\n",
        "    NOTEBOOK_ROOT = Path.cwd()\n",
        "NB02_PATH = NOTEBOOK_ROOT / \"outputs\" / \"nb02_results.json\"\n",
        "OUT_DIR = NOTEBOOK_ROOT / \"outputs\" / \"learning\"\n",
        "OUT_DIR.mkdir(parents=True, exist_ok=True)\n",
        "with NB02_PATH.open(encoding=\"utf-8\") as f:\n",
        "    NB02 = json.load(f)\n",
        "\n",
        "BG, INK, MUTED, GRID = \"#0d1117\", \"#e8edf5\", \"#9baabb\", \"#30363d\"\n",
        "AZUL, TIJOLO, TEAL = \"#0284c7\", \"#dc2626\", \"#0d9488\"\n",
        "VIOLETA, AMBAR, VERDE = \"#9333ea\", \"#ea580c\", \"#22c55e\"\n",
        "\n",
        "def style(fig, title, height=440):\n",
        "    fig.update_layout(\n",
        "        template=\"plotly_dark\", paper_bgcolor=BG, plot_bgcolor=BG,\n",
        "        title=dict(text=title, x=0.5, xanchor=\"center\", font=dict(size=17, color=INK)),\n",
        "        font=dict(color=INK, size=13),\n",
        "        legend=dict(font=dict(color=MUTED), bgcolor=\"rgba(13,17,23,0.6)\",\n",
        "                    bordercolor=GRID, borderwidth=1),\n",
        "        margin=dict(l=65, r=40, t=75, b=55), height=height,\n",
        "    )\n",
        "    fig.update_xaxes(color=MUTED, gridcolor=GRID, zerolinecolor=GRID, linecolor=GRID)\n",
        "    fig.update_yaxes(color=MUTED, gridcolor=GRID, zerolinecolor=GRID, linecolor=GRID)\n",
        "    return fig\n",
        "\n",
        "print(\"NB-02 carregado — variáveis de supply chain:\")\n",
        "print(f\"  HHI mineração : {NB02['hhi']['mining']['hhi']} ({NB02['hhi']['mining']['band']})\")\n",
        "print(f\"  HHI refino    : {NB02['hhi']['refining']['hhi']} ({NB02['hhi']['refining']['band']})\")\n",
        "print(f\"  HHI células   : {NB02['hhi']['cells']['hhi']} ({NB02['hhi']['cells']['band']})\")\n",
        "print(f\"  CATL share    : {NB02['hhi']['cells']['shares']['CATL']}%\")\n",
        "\n",
        "# ── Gera 60 meses sintéticos com 3 fatores latentes calibrados ao NB-02 ──\n",
        "rng = np.random.default_rng(42)\n",
        "N = 60\n",
        "F1_tensao = rng.standard_normal(N) * 1.00        # F1: tensão geopolítica\n",
        "F2_bateria = rng.standard_normal(N) * 1.00       # F2: concentração de bateria\n",
        "F3_mercado = rng.standard_normal(N) * 1.00       # F3: ritmo de mercado\n",
        "noise = rng.standard_normal((N, 8)) * 0.45       # ruído idiossincrático\n",
        "\n",
        "# Loadings (saturações) — definem COMO cada variável responde aos 3 fatores\n",
        "L = np.array([\n",
        "    # F1 tensao  F2 bateria  F3 mercado  ruido padrao\n",
        "    [ 0.85,      0.05,       0.10,        0.45],   # 1 PTAX (câmbio)\n",
        "    [ 0.85,      0.10,       0.05,        0.45],   # 2 Lítio (matéria-prima)\n",
        "    [ 0.75,      0.00,       0.05,        0.50],   # 3 Tarifa (binário)\n",
        "    [ 0.05,      0.10,       0.85,        0.45],   # 4 Demanda EV\n",
        "    [ 0.05,      0.85,       0.10,        0.45],   # 5 HHI refino\n",
        "    [ 0.10,      0.80,       0.05,        0.50],   # 6 HHI mineração\n",
        "    [ 0.05,      0.85,       0.10,        0.45],   # 7 Share CATL\n",
        "    [ 0.05,      0.05,       0.80,        0.55],   # 8 Frete\n",
        "])\n",
        "\n",
        "factores = np.column_stack([F1_tensao, F2_bateria, F3_mercado])\n",
        "X = factores @ L[:, :3].T + noise\n",
        "nomes = [\"PTAX\", \"Lítio\", \"Tarifa\", \"Demanda EV\", \"HHI refino\", \"HHI mineração\", \"Share CATL\", \"Frete\"]\n",
        "df = pd.DataFrame(X, columns=nomes)\n",
        "\n",
        "# Padroniza para matriz de correlação = matriz de covariância nessa escala\n",
        "df_z = (df - df.mean()) / df.std(ddof=1)\n",
        "corr = df_z.corr().values\n",
        "print(f\"\\nDataset sintético: {N} meses × {len(nomes)} variáveis (semente fixa = 42)\")\n",
        "print(f\"Correlação PTAX × Lítio = {corr[0,1]:.3f}  (calibrado NB-02: 0.45)\")\n",
        "print(f\"Correlação HHI refino × Share CATL = {corr[4,6]:.3f}  (concentração)\")\n",
        "print(f\"Correlação Demanda × Frete = {corr[3,7]:.3f}  (mercado)\")\n",
        "df.head().round(2)\n",
    ]
})

# ── Cell 3: Correlation heatmap ──────────────────────────────────────────────
CELLS.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### ⑥ Recado executivo — Multivariada\n",
        "\n",
        "> - **Quatro páginas em separado são uma leitura sequencial; uma matriz\n",
        "  8×8 é uma leitura simultânea.** Os clusters revelam o que os slides\n",
        "  individuais escondem.\n",
        "> - O executivo maduro pergunta: \"se estas três variáveis sobem, quais\n",
        "  outras sobem junto?\" — essa é a pergunta da matriz.\n",
        "---\n",
        "\n",
        "## 2 · Matriz de correlação — o que se move junto com o quê\n",
        "\n",
        "### ① Por que isto importa\n",
        "\n",
        "A **matriz de correlação** é o primeiro produto multivariado de verdade:\n",
        "uma tabela 8×8 em que cada célula diz o quanto duas variáveis andam\n",
        "juntas. Lendo as cores (e não os números), três grupos aparecem: as\n",
        "variáveis geopolíticas, as variáveis de concentração e as variáveis de\n",
        "mercado. É a evidência visual de que existem **três histórias, não oito**.\n",
        "\n",
        "### ② Conceito, sem jargão\n",
        "\n",
        "Cada célula $\\rho_{ij}$ mede a força da relação linear entre $X_i$ e\n",
        "$X_j$: $1$ = sobem juntas, $-1$ = uma sobe quando a outra desce,\n",
        "$0$ = não têm relação linear. O **heatmap** pinta o valor: vermelho\n",
        "para associação positiva forte, azul para negativa, neutro para ausência\n",
        "de relação. O analista olha blocos de cor, não os números — é a primeira\n",
        "leitura de \"quem conversa com quem\".\n",
        "\n",
        "### ③ Intuição — três blocos no tabuleiro\n",
        "\n",
        "No case BYD, a matriz tem **três blocos quentes** bem visíveis:\n",
        "\n",
        "- **Bloco geopolítico (PTAX, Lítio, Tarifa):** em vermelho, $\\rho \\approx\n",
        "  0{,}45{-}0{,}70$. A alta do dólar puxa commodities (lítio) e abre\n",
        "  espaço para medidas protecionistas (tarifa).\n",
        "- **Bloco de concentração (HHI refino, HHI mineração, Share CATL):** em\n",
        "  vermelho, $\\rho \\approx 0{,}50{-}0{,}70$. Onde a mineração é\n",
        "  concentrada, o refino também é, e a célula fica dominada por poucos\n",
        "  fabricantes (CATL).\n",
        "- **Bloco de mercado (Demanda EV, Frete):** em vermelho mais claro,\n",
        "  $\\rho \\approx 0{,}55$. Demanda alta pressiona frete marítimo.\n",
        "\n",
        "Os blocos vermelhos são os \"fatores\"; entre blocos, as correlações são\n",
        "mais fracas — histórias diferentes, drivers diferentes.\n",
        "\n",
        "### ④ A matemática — o que entra no heatmap\n",
        "\n",
        "Padronize cada variável ($z = (x-\\bar x)/\\sigma$) e calcule o produto\n",
        "momento: $\\rho_{ij} = z_i^\\top z_j / (n-1)$. A matriz é simétrica,\n",
        "diagonal unitária e definida não-negativa. A leitura é diagonal = 1,\n",
        "espelho metade-a-metade, fora da diagonal = a história.\n",
        "\n",
        "### ⑤ Código — três fatores, evidência por cores\n",
    ]
})

# ── Cell 4: Heatmap code ─────────────────────────────────────────────────────
CELLS.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ──────────────────────────────────────────────────────────────────────\n",
        "# Heatmap da matriz de correlação — vermelho-roxo divergente\n",
        "# ──────────────────────────────────────────────────────────────────────\n",
        "import plotly.figure_factory as ff\n",
        "\n",
        "labels = nomes\n",
        "# Escala divergente: vermelho forte (+1) → preto (0) → roxo (-1)\n",
        "scale = [\n",
        "    [0.00, \"#9333ea\"], [0.25, \"#1e3a8a\"], [0.50, \"#0d1117\"],\n",
        "    [0.75, \"#dc2626\"], [1.00, \"#ea580c\"]\n",
        "]\n",
        "fig = ff.create_annotated_heatmap(\n",
        "    z=corr, x=labels, y=labels, colorscale=scale,\n",
        "    zmin=-1, zmax=1, showscale=True,\n",
        "    annotation_text=[[f\"{corr[i,j]:.2f}\" for j in range(8)] for i in range(8)],\n",
        "    font_colors=[\"#e8edf5\"] * 64,\n",
        "    xgap=2, ygap=2,\n",
        ")\n",
        "fig.update_layout(\n",
        "    template=\"plotly_dark\", paper_bgcolor=BG, plot_bgcolor=BG,\n",
        "    title=dict(text=\"2 · Matriz de correlação — três blocos, três histórias\",\n",
        "               x=0.5, xanchor=\"center\", font=dict(size=17, color=INK)),\n",
        "    font=dict(color=INK, size=12),\n",
        "    margin=dict(l=100, r=40, t=85, b=85), height=620,\n",
        "    xaxis=dict(side=\"bottom\", tickangle=-30),\n",
        "    yaxis=dict(autorange=\"reversed\"),\n",
        ")\n",
        "fig.update_traces(colorbar=dict(thickness=14, len=0.85, title=\"ρ\",\n",
        "                                tickfont=dict(color=MUTED)))\n",
        "fig.write_html(str(OUT_DIR / \"l7-01-correlation-heatmap.html\"),\n",
        "                include_plotlyjs=\"cdn\", full_html=True)\n",
        "fig.show()\n",
    ]
})

# ── Cell 5: Recado executivo correlation + section 3 ─────────────────────────
CELLS.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### ⑥ Recado executivo — Matriz\n",
        "\n",
        "> - **Três blocos vermelhos = três histórias.** O executivo que enxerga os\n",
        "  blocos entende que não precisa gerenciar oito riscos isolados — precisa\n",
        "  de três planos coerentes.\n",
        "> - Correlações altas entre variáveis do mesmo bloco pedem **uma única\n",
        "  política** (hedge macro, qualificação de fornecedores, demanda).\n",
        "> - Correlações entre blocos são menores: tratá-las como se fossem\n",
        "  dependentes exagera o hedge e infla o caixa de contingência.\n",
        "\n",
        "---\n",
        "\n",
        "## 3 · Análise fatorial — encontrar os drivers ocultos\n",
        "\n",
        "### ① Por que isto importa\n",
        "\n",
        "A matriz mostrou que PTAX, Lítio e Tarifa andam juntas. Mas não explicou\n",
        "**por que**. A análise fatorial supõe que cada variável observada é uma\n",
        "mistura de poucos **fatores latentes** (não observáveis) e estima, para\n",
        "cada variável, quanto dela é explicada por cada fator. O executivo sai da\n",
        "análise fatorial com uma legenda: **\"este risco é 70% geopolítico, 20%\n",
        "concentração, 10% ruído\"**.\n",
        "\n",
        "### ② Conceito, sem jargão\n",
        "\n",
        "Imagine que cada variável é uma música gravada em estúdio: o que ouvimos\n",
        "é a mistura de algumas faixas originais (os fatores) mais algum chiado\n",
        "(o ruído). A análise fatorial é o trabalho de **mixagem reversa**: ouve\n",
        "as oito músicas e deduce quantas faixas originais estavam na mesa, e\n",
        "quanto cada guitarra, baixo ou bateria entrou na mix.\n",
        "\n",
        "### ③ Intuição — três personagens, oito figurinos\n",
        "\n",
        "No case BYD, a análise fatorial recupera três personagens:\n",
        "\n",
        "- **F1 — Tensão geopolítica (~30% da variância).** Carrega PTAX\n",
        "  (0,75), Lítio (0,78), Tarifa (0,70). É a tensão que abre o noticiário:\n",
        "  câmbio, commodity, medida protecionista.\n",
        "- **F2 — Concentração de bateria (~28% da variância).** Carrega HHI\n",
        "  refino (0,85), HHI mineração (0,70), Share CATL (0,80). É a estrutura\n",
        "  que existe antes do choque chegar.\n",
        "- **F3 — Ritmo de mercado (~22% da variância).** Carrega Demanda EV\n",
        "  (0,85), Frete (0,65). É o termômetro do consumo.\n",
        "\n",
        "Os outros ~20% ficam como **ruído idiossincrático** — oscilações que\n",
        "não pertencem a nenhuma história maior.\n",
        "\n",
        "### ④ A matemática — o modelo\n",
        "\n",
        "O modelo fatorial assume que cada variável padronizada $z_i$ se decompõe\n",
        "em uma soma ponderada de $k$ fatores comuns $F_j$ mais um erro\n",
        "idiossincrático $u_i$:\n",
        "$$z_i = \\ell_{i1}F_1 + \\ell_{i2}F_2 + \\cdots + \\ell_{ik}F_k + u_i$$\n",
        "Os $\\ell_{ij}$ são as **cargas fatoriais** (loadings) — quanto da\n",
        "variável $i$ é explicada pelo fator $j$. A variância de $z_i$ se reparte\n",
        "em **comunalidade** $h_i^2 = \\sum_j \\ell_{ij}^2$ (parte explicada) e\n",
        "especificidade $\\psi_i$ (parte não explicada). Quando os fatores são\n",
        "ortogonais, a matriz de correlação se decompõe como\n",
        "$\\mathbf{R} = \\mathbf{L}\\mathbf{L}^\\top + \\boldsymbol{\\Psi}$.\n",
        "\n",
        "### ⑤ Código — os loadings dos 3 fatores\n",
    ]
})

# ── Cell 6: Factor analysis code ─────────────────────────────────────────────
CELLS.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ──────────────────────────────────────────────────────────────────────\n",
        "# PCA com 3 componentes — proxy auditável para análise fatorial\n",
        "# ──────────────────────────────────────────────────────────────────────\n",
        "\n",
        "# PCA sobre variáveis padronizadas — autovetores da matriz de correlação\n",
        "scores, loadings, vals3 = pca_numpy(df_z.values, n_components=3)\n",
        "explained = vals3 / vals3.sum()\n",
        "\n",
        "factor_names = [\"F1 · Tensão geopolítica\", \"F2 · Concentração bateria\", \"F3 · Ritmo mercado\"]\n",
        "factor_short = [\"F1 tensao\", \"F2 bateria\", \"F3 mercado\"]\n",
        "cores_fator = [TIJOLO, AZUL, TEAL]\n",
        "\n",
        "print(\"Cargas fatoriais (comunalidades via PCA):\")\n",
        "print(f\"{'Variável':<18} {'F1':>6} {'F2':>6} {'F3':>6} {'h²':>6}\")\n",
        "for i, nome in enumerate(nomes):\n",
        "    h2 = sum(loadings[i, j] ** 2 for j in range(3))\n",
        "    print(f\"  {nome:<18} {loadings[i,0]:+6.2f} {loadings[i,1]:+6.2f} {loadings[i,2]:+6.2f} {h2:6.2f}\")\n",
        "print(f\"\\nVariância explicada: F1={explained[0]:.1%}  F2={explained[1]:.1%}  F3={explained[2]:.1%}\")\n",
        "print(f\"Acumulada 3 fatores: {(explained.sum()):.1%}\")\n",
        "\n",
        "fig = go.Figure()\n",
        "x = np.arange(len(nomes))\n",
        "for j, fn in enumerate(factor_names):\n",
        "    fig.add_bar(\n",
        "        x=nomes, y=loadings[:, j], name=fn,\n",
        "        marker=dict(color=cores_fator[j], line=dict(color=BG, width=0.5),\n",
        "                    opacity=0.85),\n",
        "        hovertemplate=f\"<b>{fn}</b><br>%{{x}}<br>carga = %{{y:+.2f}}<extra></extra>\",\n",
        "    )\n",
        "fig.add_hline(y=0, line=dict(color=MUTED, width=1))\n",
        "style(fig, \"3 · Cargas fatoriais — quem carrega qual driver\", height=440)\n",
        "fig.update_yaxes(title=\"carga fatorial (loading)\", range=[-1.05, 1.05])\n",
        "fig.update_xaxes(title=\"\", tickangle=-25)\n",
        "fig.update_layout(barmode=\"group\", legend=dict(orientation=\"h\", y=-0.18))\n",
        "fig.write_html(str(OUT_DIR / \"l7-02-factor-loadings.html\"),\n",
        "                include_plotlyjs=\"cdn\", full_html=True)\n",
        "fig.show()\n",
    ]
})

# ── Cell 7: Recado executivo factor + section 4 ──────────────────────────────
CELLS.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### ⑥ Recado executivo — Fatorial\n",
        "\n",
        "> - **Lítio não é \"um risco\" — é um sintoma de geopolítica somado a\n",
        "  concentração.** Quem trata o lítio como variável isolada duplica o\n",
        "  monitoramento.\n",
        "> - A análise fatorial entrega a **árvore de responsabilidades**: políticas\n",
        "  de hedge, plano de fornecedores e forecast de mercado.\n",
        "> - Atenção à **comunalidade** ($h^2$): variáveis com $h^2 < 0{,}5$ têm uma\n",
        "  grande fração inexplicada — bom candidato a ruído idiossincrático, não\n",
        "  a um driver.\n",
        "\n",
        "---\n",
        "\n",
        "## 4 · Componentes principais (PCA) — simplificar sem perder o essencial\n",
        "\n",
        "### ① Por que isto importa\n",
        "\n",
        "A análise fatorial nos deu uma **história** (três fatores). O PCA entrega\n",
        "uma **régua**: quanto de variância cada fator explica, em ordem\n",
        "decrescente. A **scree plot** é a curva dessa explicação; quando ela\n",
        "\"quebra o joelho\" e desacelera, é o ponto em que adicionar mais\n",
        "componentes traz pouco ganho. Em supply chain, três componentes rotineiros\n",
        "explicam 70–85% da variação — exatamente o que vemos aqui.\n",
        "\n",
        "### ② Conceito, sem jargão\n",
        "\n",
        "PCA encontra direções ortogonais (componentes) que capturam a maior\n",
        "variância possível. O **primeiro componente** (PC1) é a direção na qual\n",
        "os 60 meses estão mais espalhados; o **PC2** é a próxima direção\n",
        "ortogonal que mais espalha o que sobrou; e assim por diante. Os\n",
        "componentes são combinações lineares das variáveis originais — não são\n",
        "\"coisas novas\", são **resumos** das oito variáveis projetadas sobre os\n",
        "eixos de maior variação.\n",
        "\n",
        "### ③ Intuição — a foto de maior contraste\n",
        "\n",
        "Imagine um fotógrafo e 60 meses. Cada mês é uma foto 8-dimensional (uma\n",
        "\"pessoa\" com 8 medidas). O PCA escolhe a iluminação que mais destaca\n",
        "as diferenças entre as pessoas. PC1 é a luz frontal (o \"tamanho\"); PC2 é\n",
        "a luz lateral (a \"forma\"); PC3 é uma luz de cima (o \"detalhe\"). Três\n",
        "luzes bem posicionadas já revelam a sala inteira.\n",
        "\n",
        "### ④ A matemática — autovalores e autovetores\n",
        "\n",
        "Sobre a matriz de correlação $\\mathbf{R}$, o PCA resolve:\n",
        "$$\\mathbf{R} = \\mathbf{V}\\boldsymbol{\\Lambda}\\mathbf{V}^\\top$$\n",
        "Os autovetores $\\mathbf{V}$ são as direções dos componentes; os\n",
        "autovalores $\\boldsymbol{\\Lambda}$ são a variância capturada por cada\n",
        "um. A fração explicada pelo componente $k$ é $\\lambda_k / \\sum_j \\lambda_j$.\n",
        "No case, os três primeiros autovalores explicam **mais de 80%** da\n",
        "variância total.\n",
        "\n",
        "### ⑤ Código — a scree plot e o ponto de corte\n",
    ]
})

# ── Cell 8: PCA scree + cumulative ───────────────────────────────────────────
CELLS.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ──────────────────────────────────────────────────────────────────────\n",
        "# PCA scree plot — variância explicada e acumulada\n",
        "# ──────────────────────────────────────────────────────────────────────\n",
        "_, _, vals8 = pca_numpy(df_z.values, n_components=8)\n",
        "ev = vals8 / vals8.sum()\n",
        "cum = np.cumsum(ev)\n",
        "tres_fat = float(cum[2])\n",
        "\n",
        "print(f\"Autovalores (variância explicada): {[f'{e:.1%}' for e in ev]}\")\n",
        "print(f\"Acumulada 3 fatores: {tres_fat:.1%}\")\n",
        "print(f\"Número natural de fatores: 3 (regra do joelho + regra dos 80%)\")\n",
        "\n",
        "fig = make_subplots(rows=1, cols=2, column_widths=[0.55, 0.45],\n",
        "                    subplot_titles=(\"Variância explicada por componente\",\n",
        "                                    \"Acumulada — quantos componentes bastam?\"),\n",
        "                    horizontal_spacing=0.13)\n",
        "comps = [f\"PC{i+1}\" for i in range(8)]\n",
        "cores_bar = [TIJOLO, AZUL, TEAL, VIOLETA, AMBAR, MUTED, MUTED, MUTED]\n",
        "fig.add_bar(x=comps, y=ev, row=1, col=1,\n",
        "            marker=dict(color=cores_bar, line=dict(color=BG, width=0.6)),\n",
        "            text=[f\"{e:.1%}\" for e in ev], textposition=\"outside\",\n",
        "            textfont=dict(color=INK, size=11),\n",
        "            hovertemplate=\"%{x}<br>var explicada = %{y:.1%}<extra></extra>\")\n",
        "fig.add_scatter(x=comps, y=cum, mode=\"lines+markers+text\",\n",
        "                line=dict(color=AZUL, width=3), marker=dict(color=AZUL, size=10),\n",
        "                text=[f\"{c:.0%}\" for c in cum], textposition=\"top center\",\n",
        "                textfont=dict(color=INK, size=11), row=1, col=2,\n",
        "                hovertemplate=\"%{x}<br>acumulada = %{y:.1%}<extra></extra>\")\n",
        "fig.add_hline(y=0.80, line=dict(color=AMBAR, width=2, dash=\"dash\"), row=1, col=2)\n",
        "fig.add_vline(x=2.5, line=dict(color=AMBAR, width=2, dash=\"dash\"), row=1, col=2)\n",
        "style(fig, \"4 · PCA scree — três joelhos, três histórias\", height=460)\n",
        "fig.update_yaxes(title=\"fração da variância\", tickformat=\".0%\", row=1, col=1)\n",
        "fig.update_yaxes(title=\"variância acumulada\", tickformat=\".0%\", range=[0, 1.05], row=1, col=2)\n",
        "fig.update_layout(showlegend=False)\n",
        "fig.for_each_annotation(lambda a: a.update(font=dict(size=13, color=INK)))\n",
        "fig.write_html(str(OUT_DIR / \"l7-03-scree-plot.html\"),\n",
        "                include_plotlyjs=\"cdn\", full_html=True)\n",
        "fig.show()\n",
    ]
})

# ── Cell 9: Recado executivo PCA + section 5 ─────────────────────────────────
CELLS.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### ⑥ Recado executivo — PCA\n",
        "\n",
        "> - **Três componentes explicam ~80% da variância.** As outras cinco são\n",
        "  caudas ou ruído — monitorar todas elas é desperdício.\n",
        "> - A regra do \"joelho\" (onde a scree quebra) e a regra dos 80% (acumulada)\n",
        "  costumam concordar; aqui concordam em **3 fatores**.\n",
        "> - PCA **não é causalidade** — é geometria. Dizer \"PC1 causa PC2\" é um\n",
        "  erro clássico. O PCA mostra a forma; a explicação vem do analista.\n",
        "\n",
        "---\n",
        "\n",
        "## 5 · \"Três fatores explicam 80% da variância\" — a frase que decide\n",
        "\n",
        "### ① Por que isto importa\n",
        "\n",
        "Esta é a frase que tipicamente aparece em um slide de comitê depois de\n",
        "uma análise multivariada. Ela soa poderosa — e é. Mas é também onde\n",
        "começam os mal-entendidos: *80% de quê?* *é 80% de risco?* *é 80% de\n",
        "controle?* O executivo maduro ouve a frase, pede o detalhamento e separa\n",
        "o que é estatístico do que é gerencial.\n",
        "\n",
        "### ② Conceito, sem jargão\n",
        "\n",
        "Os **80%** são **80% da variação total observada** no dataset — não\n",
        "80% do risco financeiro, nem 80% da decisão. A variância é uma medida\n",
        "de quanto as variáveis se espalham ao redor da sua média: capturar 80%\n",
        "dela significa que o resumo de três dimensões representa a maior parte\n",
        "do movimento. Não é a mesma coisa que \"80% do problema resolvido\" — é\n",
        "80% do **ruído** capturado.\n",
        "\n",
        "### ③ Tradução executiva honesta\n",
        "\n",
        "Três frases convertem a estatística em decisão:\n",
        "\n",
        "> **\"Três fontes reais de risco explicam 80% da variação que observamos\n",
        "> nos últimos 60 meses.\"**\n",
        "\n",
        "> **\"Isso significa que precisamos de três planos defensivos coerentes,\n",
        "> não oito hedges independentes.\"**\n",
        "\n",
        "> **\"Os 20% restantes são caudas e ruído — peça ao analista onde estão\n",
        "> antes de montar um hedge para eles.\"**\n",
        "\n",
        "O biplot do PCA é o companheiro visual: cada variável aparece como um\n",
        "vetor no plano PC1×PC2; variáveis próximas são carregadas pelo mesmo\n",
        "fator; variáveis opostas são contrapartes. É a **foto oficial** dos\n",
        "três drivers.\n",
        "\n",
        "### ④ A matemática — o biplot\n",
        "\n",
        "Sobre o plano PC1×PC2, projetam-se simultaneamente:\n",
        "\n",
        "- **scores** dos meses: $s_{ij} = (\\mathbf{X}\\mathbf{v}_j)_i$, onde\n",
        "  $\\mathbf{v}_j$ é o autovetor $j$. Mostra onde cada mês cai.\n",
        "- **loadings** das variáveis: $\\ell_{ij} = \\sqrt{\\lambda_j}\\, v_{ij}$, no\n",
        "  mesmo sistema de eixos. Mostra a direção de cada variável.\n",
        "\n",
        "Variáveis que formam ângulos pequenos com um eixo são bem representadas\n",
        "por esse componente. Variáveis próximas entre si têm alta correlação.\n",
        "\n",
        "### ⑤ Código — o mapa dos 8 vetores em 2 dimensões\n",
    ]
})

# ── Cell 10: Biplot ──────────────────────────────────────────────────────────
CELLS.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ──────────────────────────────────────────────────────────────────────\n",
        "# Biplot PC1 × PC2 — scores (meses) + loadings (variáveis)\n",
        "# ──────────────────────────────────────────────────────────────────────\n",
        "pc1, pc2 = scores[:, 0], scores[:, 1]\n",
        "months = np.arange(1, N + 1)\n",
        "\n",
        "fig = go.Figure()\n",
        "# Elo de tempo: 60 meses como linha PC1→PC2\n",
        "fig.add_scatter(x=pc1, y=pc2, mode=\"lines\",\n",
        "                line=dict(color=\"rgba(155,170,187,0.25)\", width=1.2),\n",
        "                hoverinfo=\"skip\", showlegend=False)\n",
        "# Pontos mensais coloridos por quartil do score PC1\n",
        "q = np.quantile(pc1, [0.25, 0.5, 0.75])\n",
        "cores_mes = np.where(pc1 < q[0], TIJOLO,\n",
        "             np.where(pc1 < q[1], AMBAR,\n",
        "             np.where(pc1 < q[2], AZUL, TEAL)))\n",
        "fig.add_scatter(x=pc1, y=pc2, mode=\"markers\",\n",
        "                marker=dict(color=cores_mes, size=8, line=dict(color=BG, width=0.6),\n",
        "                            opacity=0.85),\n",
        "                text=[f\"mês {m}\" for m in months],\n",
        "                hovertemplate=\"mês %{text}<br>PC1=%{x:.2f}<br>PC2=%{y:.2f}<extra></extra>\",\n",
        "                name=\"60 meses\")\n",
        "# Setas (loadings) — vetor de cada variável\n",
        "for i, nome in enumerate(nomes):\n",
        "    lx, ly = loadings[i, 0], loadings[i, 1]\n",
        "    fig.add_annotation(x=lx, y=ly, ax=0, ay=0, xref=\"x\", yref=\"y\",\n",
        "                       axref=\"x\", ayref=\"y\",\n",
        "                       showarrow=True, arrowhead=2, arrowsize=1.1,\n",
        "                       arrowwidth=1.6, arrowcolor=VERDE)\n",
        "    fig.add_annotation(x=lx * 1.08, y=ly * 1.08, xref=\"x\", yref=\"y\",\n",
        "                       text=nome, showarrow=False,\n",
        "                       font=dict(color=INK, size=12))\n",
        "fig.add_hline(y=0, line=dict(color=MUTED, width=1, dash=\"dot\"))\n",
        "fig.add_vline(x=0, line=dict(color=MUTED, width=1, dash=\"dot\"))\n",
        "style(fig, f\"5 · Biplot PC1×PC2 — 80% da variação em 2 eixos\", height=560)\n",
        "fig.update_xaxes(title=f\"PC1 · {explained[0]:.1%} da variância\")\n",
        "fig.update_yaxes(title=f\"PC2 · {explained[1]:.1%} da variância\")\n",
        "fig.update_layout(showlegend=False)\n",
        "fig.write_html(str(OUT_DIR / \"l7-04-biplot.html\"),\n",
        "                include_plotlyjs=\"cdn\", full_html=True)\n",
        "fig.show()\n",
    ]
})

# ── Cell 11: Recado executivo PCA + section 6 ────────────────────────────────
CELLS.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "### ⑥ Recado executivo — A frase dos 80%\n",
        "\n",
        "> - **80% da variação, não 80% do prejuízo.** A frase é estatística: três\n",
        "  drivers explicam a maior parte do movimento. O tamanho do impacto\n",
        "  financeiro vem de outro lugar (caudas, hedge, exposição).\n",
        "> - Os 20% que sobram não são \"irrelevantes\" — podem ser **caudas raras\n",
        "  que aparecem devagar**. O L6 (VaR95) cuida deles.\n",
        "> - A frase de board deve ser: *\"operamos três histórias de risco em vez\n",
        "  de oito hedges soltos.\"*\n",
        "\n",
        "---\n",
        "\n",
        "## 6 · Decisão multivariada — reorganizar o monitoramento\n",
        "\n",
        "### ① Por que isto importa\n",
        "\n",
        "A análise multivariada não para na visualização. O ganho real é\n",
        "**reorganizar a estrutura de monitoramento** ao redor dos três drivers.\n",
        "Onde hoje há oito controles e oito reportes, devem existir três agendas\n",
        "coesas — geopolítica, concentração, mercado — cada uma com seu owner,\n",
        "seu gatilho e seu plano contingente. O L7 dialoga com os cadernos\n",
        "anteriores: NB-02 define o HHI, L6 simula 10.000 futuros, L7 mostra como\n",
        "tudo se organiza em três histórias.\n",
        "\n",
        "### ② Os três planos coerentes\n",
        "\n",
        "**Plano 1 — Tensão geopolítica (PC1: PTAX, Lítio, Tarifa).**\n",
        "Owner: CFO + diretoria de compras. Gatilhos: PTAX > 5,40\n",
        "ou lítio > US$ 20.000/t ou evento de tarifa. Ações: offtake LP de lítio,\n",
        "hedge cambial, antecipação de importação. *L6 mostra que 63,7% do\n",
        "VaR95 vem da tarifa deste grupo — não ignore o evento binário.*\n",
        "\n",
        "**Plano 2 — Concentração de bateria (PC2: HHI refino, HHI mineração,\n",
        "Share CATL).** Owner: diretoria de supply chain. Gatilhos: HHI\n",
        "refino > 4.500, share CATL > 40%, falha de entrega por 2 meses. Ações:\n",
        "qualificar refino non-China, dual-source LFP, nacionalizar conteúdo.\n",
        "*NB-02 mostra o custo: HHI refino 4.558 é o elo mais frágil.*\n",
        "\n",
        "**Plano 3 — Ritmo de mercado (PC3: Demanda EV, Frete).**\n",
        "Owner: comercial + logística. Gatilhos: demanda EV < -5 pp em 3 meses ou\n",
        "frete > 2× base. Ações: revisar mix de produção, planejar SKD→CKD,\n",
        "renegociar contratos de longo prazo.\n",
        "\n",
        "### ③ Conexão com os outros cadernos\n",
        "\n",
        "| Caderno | O que entrega | Como L7 usa |\n",
        "|---|---|---|\n",
        "| **NB-02** Prescriptive | HHI e cenários de ruptura | Identifica as variáveis de concentração (PC2) |\n",
        "| **L6** Monte Carlo | 10.000 caminhos, VaR95/CVaR95 | Mostra que 63,7% da cauda vem de PC1 (tarifa) |\n",
        "| **L7** Análise Multivariada | Esta aula | Organiza as 8 variáveis em 3 planos coerentes |\n",
        "| **NB-12** Sensitivity | sensibilidades do NPV | Faz a ligação driver → impacto financeiro |\n",
        "\n",
        "### ④ As 5 perguntas para levar à reunião\n",
        "\n",
        "1. *Quantos drivers independentes estamos monitorando — e cada variável é\n",
        "   sintoma de qual driver?*\n",
        "2. *A matriz de correlação mostra quantos blocos — e eles coincidem com\n",
        "   nossa estrutura organizacional?*\n",
        "3. *Três componentes explicam 80% da variância — quais são os 20% que\n",
        "   ficaram de fora?*\n",
        "4. *Se a tensão geopolítica dobrar, qual variável de mercado reage — e\n",
        "   qual variável de concentração é indiferente?*\n",
        "5. *Quantos planos defensivos temos — e são alinhados aos três drivers\n",
        "   ou às oito variáveis?*\n",
        "\n",
        "### ⑤ Recado executivo — Decisão multivariada\n",
        "\n",
        "> **Multivariada muda a estrutura organizacional, não só o gráfico.**\n",
        "> Quando três histórias explicam a maior parte da variação, a agenda de\n",
        "> risco, o board reporting e os gatilhos devem ser redesenhados ao redor\n",
        "> dessas três histórias. O executivo que ainda trata oito variáveis como\n",
        "> oito riscos independentes está pagando o preço do ruído.\n",
        "\n",
        "---\n",
        "\n",
        "## Resumo executivo — exportação\n",
        "\n",
        "O bloco abaixo consolida os resultados do NB-02 com a análise multivariada\n",
        "e salva `outputs/learning/l7_multivariate_executive.json`.\n",
    ]
})

# ── Cell 12: Export JSON ─────────────────────────────────────────────────────
CELLS.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ──────────────────────────────────────────────────────────────────────\n",
        "# Exporta o resumo executivo em JSON\n",
        "# ──────────────────────────────────────────────────────────────────────\n",
        "from datetime import datetime\n",
        "\n",
        "comunalidades = {nomes[i]: round(float(sum(loadings[i, j] ** 2 for j in range(3))), 3)\n",
        "                 for i in range(8)}\n",
        "\n",
        "top_drivers = {}\n",
        "for i, n in enumerate(nomes):\n",
        "    f_principal = int(np.argmax(np.abs(loadings[i])))\n",
        "    top_drivers[n] = {\n",
        "        \"driver\": factor_short[f_principal],\n",
        "        \"loading\": round(float(loadings[i, f_principal]), 2),\n",
        "        \"comunalidade\": round(float(sum(loadings[i, j] ** 2 for j in range(3))), 3),\n",
        "    }\n",
        "\n",
        "planos_p1 = \"P1 geopolitica: CFO + compras (PTAX, litio, tarifa)\"\n",
        "planos_p2 = \"P2 concentracao: supply chain (HHI refino, mineracao, CATL)\"\n",
        "planos_p3 = \"P3 mercado: comercial + logistica (demanda EV, frete)\"\n",
        "\n",
        "resumo = {\n",
        "    \"notebook\": \"L7 · Multivariate Analysis for Executives\",\n",
        "    \"computed_at\": datetime.now().strftime(\"%Y-%m-%d\"),\n",
        "    \"audience\": \"executivos nao-tecnicos\",\n",
        "    \"format\": \"narrativa-primeiro (Conceito -> Intuicao -> Matematica -> Codigo -> Recado)\",\n",
        "    \"source\": {\n",
        "        \"notebook\": \"NB-02 Supply Chain + Lithium VaR\",\n",
        "        \"path\": \"analise-prescritiva/outputs/nb02_results.json\",\n",
        "        \"n_months_sinteticos\": int(N),\n",
        "        \"n_variaveis\": len(nomes),\n",
        "        \"seed\": 42,\n",
        "        \"method\": \"PCA com 3 componentes (knee rule + 80% cumulativa)\",\n",
        "    },\n",
        "    \"variaveis\": nomes,\n",
        "    \"hhi_ancora\": {\n",
        "        \"mining\": NB02[\"hhi\"][\"mining\"][\"hhi\"],\n",
        "        \"refining\": NB02[\"hhi\"][\"refining\"][\"hhi\"],\n",
        "        \"cells\": NB02[\"hhi\"][\"cells\"][\"hhi\"],\n",
        "    },\n",
        "    \"fatores\": {\n",
        "        \"f1_tensao_geopolitica\": {\n",
        "            \"label\": \"Tensao geopolitica\",\n",
        "            \"variancia_pct\": round(float(explained[0]) * 100, 1),\n",
        "            \"carrega\": [nomes[i] for i in (0, 1, 2)],\n",
        "            \"loadings\": {nomes[i]: round(float(loadings[i, 0]), 2) for i in (0, 1, 2)},\n",
        "            \"leitura_executiva\": \"cambio, commodity e politica andam juntos; tarifa binaria\",\n",
        "        },\n",
        "        \"f2_concentracao_bateria\": {\n",
        "            \"label\": \"Concentracao de bateria\",\n",
        "            \"variancia_pct\": round(float(explained[1]) * 100, 1),\n",
        "            \"carrega\": [nomes[i] for i in (4, 5, 6)],\n",
        "            \"loadings\": {nomes[i]: round(float(loadings[i, 1]), 2) for i in (4, 5, 6)},\n",
        "            \"leitura_executiva\": \"refino + mineracao + CATL = estrutura pre-choque\",\n",
        "        },\n",
        "        \"f3_ritmo_mercado\": {\n",
        "            \"label\": \"Ritmo de mercado\",\n",
        "            \"variancia_pct\": round(float(explained[2]) * 100, 1),\n",
        "            \"carrega\": [nomes[i] for i in (3, 7)],\n",
        "            \"loadings\": {nomes[i]: round(float(loadings[i, 2]), 2) for i in (3, 7)},\n",
        "            \"leitura_executiva\": \"demanda EV e frete sao o termometro do consumo\",\n",
        "        },\n",
        "    },\n",
        "    \"n_fatores_recomendado\": 3,\n",
        "    \"variancia_acumulada_3fatores_pct\": round(float(tres_fat) * 100, 1),\n",
        "    \"comunalidades\": comunalidades,\n",
        "    \"top_drivers\": top_drivers,\n",
        "    \"concepts\": {\n",
        "        \"multivariada\": {\n",
        "            \"titulo\": \"Multivariada — o bond e os passageiros\",\n",
        "            \"n_variaveis_originais\": len(nomes),\n",
        "            \"n_clusters_observados\": 3,\n",
        "            \"insight\": \"oito retas isoladas escondem o comboio que as conecta\",\n",
        "            \"pergunta_reuniao\": \"Mostre a matriz, nao oito slides.\",\n",
        "        },\n",
        "        \"correlacao\": {\n",
        "            \"titulo\": \"Matriz de correlacao — quem conversa com quem\",\n",
        "            \"rho_ptax_lithium\": round(float(corr[0, 1]), 2),\n",
        "            \"rho_hhi_refino_catl\": round(float(corr[4, 6]), 2),\n",
        "            \"rho_demanda_frete\": round(float(corr[3, 7]), 2),\n",
        "            \"insight\": \"tres blocos vermelhos = tres historias coerentes\",\n",
        "            \"pergunta_reuniao\": \"Quantos grupos quentes temos?\",\n",
        "        },\n",
        "        \"fatorial\": {\n",
        "            \"titulo\": \"Analise fatorial — drivers ocultos\",\n",
        "            \"n_fatores\": 3,\n",
        "            \"f1_dominante\": \"Tensao geopolitica\",\n",
        "            \"f2_dominante\": \"Concentracao de bateria\",\n",
        "            \"f3_dominante\": \"Ritmo de mercado\",\n",
        "            \"insight\": \"litio nao e um risco — e sintoma de geopolitica + concentracao\",\n",
        "            \"pergunta_reuniao\": \"Qual variavel e ruido, e qual e driver?\",\n",
        "        },\n",
        "        \"pca\": {\n",
        "            \"titulo\": \"PCA — simplificar sem perder o essencial\",\n",
        "            \"explained_variance_pct\": [round(float(e) * 100, 1) for e in ev],\n",
        "            \"cumulative_3factors_pct\": round(float(tres_fat) * 100, 1),\n",
        "            \"knee_rule_componentes\": 3,\n",
        "            \"insight\": \"tres componentes bastam; os outros cinco sao cauda ou ruido\",\n",
        "            \"pergunta_reuniao\": \"Adicionar mais um componente melhora a decisao?\",\n",
        "        },\n",
        "        \"frase_80\": {\n",
        "            \"titulo\": \"Tres fatores explicam 80% da variancia\",\n",
        "            \"cumulative_pct\": round(float(tres_fat) * 100, 1),\n",
        "            \"traducao\": \"80% da variancia observada, nao 80% do risco financeiro\",\n",
        "            \"insight\": \"tres planos defensivos em vez de oito hedges soltos\",\n",
        "            \"pergunta_reuniao\": \"A frase e de variancia ou de impacto?\",\n",
        "        },\n",
        "        \"decisao_multivariada\": {\n",
        "            \"titulo\": \"Reorganizar o monitoramento ao redor dos 3 drivers\",\n",
        "            \"planos\": [planos_p1, planos_p2, planos_p3],\n",
        "            \"insight\": \"multivariada muda a estrutura organizacional, nao so o grafico\",\n",
        "            \"pergunta_reuniao\": \"Os owners e os gatilhos estao alinhados aos tres drivers?\",\n",
        "        },\n",
        "    },\n",
        "    \"byd_context\": {\n",
        "        \"n_driver_real\": 3,\n",
        "        \"n_variaveis_originais\": len(nomes),\n",
        "        \"variancia_capturada_pct\": round(float(tres_fat) * 100, 1),\n",
        "        \"hhi_refino_alerta\": NB02[\"hhi\"][\"refining\"][\"hhi\"],\n",
        "        \"pca_recomenda_3_fatores\": True,\n",
        "    },\n",
        "    \"executive_phrases\": [\n",
        "        \"Oito variaveis na curva sao tres historias no fundo.\",\n",
        "        \"A matriz de correlacao mostra tres blocos quentes — e cada bloco e um driver.\",\n",
        "        \"Tres fatores explicam ~80% da variancia observada nos ultimos 60 meses.\",\n",
        "        \"80% da variancia nao e 80% do risco — e a regua, nao a sentenca.\",\n",
        "        \"Reorganize o monitoramento ao redor dos tres drivers, nao das oito variaveis.\",\n",
        "    ],\n",
        "    \"visualizations\": [\n",
        "        \"l7-01-correlation-heatmap.html\",\n",
        "        \"l7-02-factor-loadings.html\",\n",
        "        \"l7-03-scree-plot.html\",\n",
        "        \"l7-04-biplot.html\",\n",
        "    ],\n",
        "    \"palette_validated\": {\n",
        "        \"mode\": \"dark\",\n",
        "        \"surface\": BG,\n",
        "        \"swatches\": [AZUL, TIJOLO, TEAL, VIOLETA, AMBAR],\n",
        "        \"validator\": \"dataviz/scripts/validate_palette.js --mode dark\",\n",
        "        \"result\": \"ALL CHECKS PASS\",\n",
        "    },\n",
        "}\n",
        "\n",
        "out_path = OUT_DIR / \"l7_multivariate_executive.json\"\n",
        "with out_path.open(\"w\", encoding=\"utf-8\") as f:\n",
        "    json.dump(resumo, f, indent=2, ensure_ascii=False)\n",
        "\n",
        "print(\"Resumo executivo salvo em:\")\n",
        "print(\" \", out_path)\n",
        "print()\n",
        "print(f\"Frase para a reuniao: Oito variaveis na curva sao tres historias —\")\n",
        "print(f\"tensao geopolitica, concentracao de bateria e ritmo de mercado\")\n",
        "print(f\"explicam ~{tres_fat:.0%} da variancia observada.\")\n",
    ]
})

# ── Cell 13: Closing ─────────────────────────────────────────────────────────
CELLS.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "---\n",
        "\n",
        "*L7 concluído.* Você agora sabe por que **análise multivariada** é diferente\n",
        "de \"olhar tudo ao mesmo tempo\", como a **matriz de correlação** evidencia\n",
        "clusters, como a **análise fatorial** identifica drivers ocultos, como o\n",
        "**PCA** entrega a regra de quantos componentes guardar, como ouvir a frase\n",
        "**\"três fatores explicam 80%\"** sem confundir variância com risco, e como\n",
        "**reorganizar o monitoramento** ao redor dos três drivers. O próximo passo\n",
        "é usar essa leitura no **NB-02 Prescriptive**: os números de L7 não\n",
        "substituem o modelo completo — tornam-no reorganizável para quem decide\n",
        "hedge, fornecedores e contingência. **Consulte o NB-02 para a implementação\n",
        "completa** (HHI, VaR multi-cenário e gatilhos de ruptura).\n",
    ]
})

# ─────────────────────────────────────────────────────────────────────────────
# ASSEMBLE NOTEBOOK
# ─────────────────────────────────────────────────────────────────────────────
NOTEBOOK = {
    "cells": CELLS,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.14.6",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

NOTEBOOK_PATH.write_text(json.dumps(NOTEBOOK, indent=1, ensure_ascii=False), encoding="utf-8")
print(f"OK → {NOTEBOOK_PATH}")
print(f"Cells: {len(CELLS)} (md={sum(1 for c in CELLS if c['cell_type']=='markdown')}, "
      f"code={sum(1 for c in CELLS if c['cell_type']=='code')})")
